// Shared shapes used across the plugin. Kept in one file since almost
// every module needs at least one of these.

export type DelimiterDisplayMode = "auto" | "show" | "hide" | "alias";

export interface Role {
	id: string;
	label: string;
	/** Explicit open/close delimiters — the current, general mechanism. */
	open?: string;
	close?: string;
	/**
	 * Legacy field: roles saved before open/close existed carry a single
	 * symmetric marker instead (`{` + marker + text + marker + `}`).
	 * Never read directly outside resolveDelims() — kept only so old
	 * saved data keeps matching without requiring the user to re-enter
	 * anything.
	 */
	marker?: string;
	color: string;
	bold: boolean;
	italic: boolean;
	underline: boolean;
	fontFamily: string;
	sizeEm: number | null;
	highlightColor: string;
	customCss: string;
	/** false = defined but inert: no matching, no decoration, no CSS. */
	enabled: boolean;
	/**
	 * True only for roles auto-generated by the "Format selection..."
	 * command (see directFormat.ts) — never set by anything the user
	 * does directly. Matches, decorates, and styles exactly like any
	 * other role (nothing downstream treats it differently); the ONLY
	 * effect is that the Settings role list skips rendering a row for
	 * it, since it has no meaningful "label" a user would recognize and
	 * isn't meant to be hand-edited.
	 */
	hidden?: boolean;
	/**
	 * How the open/close delimiters themselves are rendered around the
	 * styled content — independent of role.enabled:
	 * - "auto" (default, undefined counts as this): current long-standing
	 *   behavior — hidden unless the cursor is inside the span (Live
	 *   Preview only; Reading view never shows raw delimiters regardless,
	 *   same as it never shows raw ** around bold text).
	 * - "show": delimiters always visible, in both views.
	 * - "hide": delimiters never visible, even while editing inside the
	 *   span (Live Preview) — a stricter always-off version of "auto".
	 * - "alias": aliasOpen/aliasClose shown in place of the real
	 *   delimiters when the cursor's outside the span; the real
	 *   delimiters reveal on focus in Live Preview (same UX as a wikilink
	 *   alias). Reading view always shows the alias (no cursor concept
	 *   there, same as a wikilink alias never reveals its target in
	 *   Reading view either).
	 */
	delimiterDisplay?: DelimiterDisplayMode;
	/** Only used when delimiterDisplay === "alias". Empty means: no alias
	 * text configured for that side, falls back to hiding it like "hide". */
	aliasOpen?: string;
	aliasClose?: string;
	/**
	 * Only meaningful when delimiterDisplay === "show" — the delimiters
	 * are visible either way in that mode, this controls whether they
	 * ALSO pick up the role's own styling (color/font/size/etc.), or stay
	 * in the plain default tag appearance every "show" role gets
	 * otherwise. Doesn't apply to "auto"/"alias" modes, where the
	 * delimiters are either hidden or replaced by alias text, not styled
	 * content, most of the time.
	 */
	styleDelimiters?: boolean;
}

export interface Delimiters {
	open: string;
	close: string;
}

export interface RoleRegex {
	role: Role;
	delims: Delimiters;
	regex: RegExp;
}

export interface RoleMatch {
	role: Role;
	matchStart: number;
	matchEnd: number;
	contentStart: number;
	contentEnd: number;
	/**
	 * Roles fully contained within this match's content — e.g. a
	 * "question" role wrapped inside a "note" role. Rendered as an
	 * actually-nested DOM element (span inside span), so properties an
	 * inner role doesn't set (color, font-family, font-weight, font-
	 * style) fall through to the outer role via ordinary CSS inheritance
	 * — no merge logic needed. Non-inherited properties like
	 * background-color correctly do NOT leak onto nested spans, which is
	 * also the wanted behavior.
	 */
	children: RoleMatch[];
}

export type HeadingAlign = "auto" | "left" | "center" | "right";

export interface HeadingStyle {
	sizeEm: number;
	color: string;
	align: HeadingAlign;
	bold: boolean;
	underline: boolean;
	fontFamily: string;
	customCss: string;
}

export type HeadingKey = "h1" | "h2" | "h3" | "h4" | "h5" | "h6";

export type HeadingStyles = Record<HeadingKey, HeadingStyle>;

export type ListBulletShape = "circle" | "square" | "diamond";

export interface TypographySettings {
	fontFamily: string;
	fontSize: number;
	lineHeight: number;
	paragraphSpacingEm: number;
	justify: boolean;
	firstLineIndent: boolean;
	firstLineIndentEm: number;
	headings: HeadingStyles;
	fileLineWidthPx: number;
	listBulletShapes: ListBulletShape[];
	footnoteSizePx: number;
}

export type ScopeMode = "global" | "cssclass" | "folder-include" | "folder-exclude" | "smart-arabic-title";

export interface ScopeSettings {
	mode: ScopeMode;
	cssclassValue: string;
	folders: string[];
}

export interface Profile {
	id: string;
	name: string;
	/** When to use this profile — shown as subtext in the "Switch profile..."
	 * picker and edited near the profile name in Settings. Purely a note
	 * to the user's future self; has no effect on matching/styling. */
	description: string;
	roles: Role[];
	typography: TypographySettings;
	scope: ScopeSettings;
	/** Hex colors offered in the right-click "Colorize" quick menu, in
	 * addition to the always-present "Custom..." option. User-declared in
	 * Settings, per-profile like everything else here. */
	quickColors: string[];
	/** Named, reusable Custom CSS fragments — a quick-pick source for the
	 * Custom CSS field in Format selection and the role editor, so a
	 * declaration like "letter-spacing: 0.05em;" doesn't need retyping
	 * every time it's wanted. User-declared in Settings, per-profile. */
	cssSnippets: { name: string; css: string }[];
}

export interface AdvancedFormattingSettings {
	profiles: Profile[];
	activeProfileId: string;
	/** Settings-pane display language only — never affects note content
	 * or the generated stylesheet. Global, not per-profile: it's a UI
	 * preference, not a typography choice. Defaults to "en". */
	uiLanguage?: "en" | "ar";
}

export interface ShapePreset {
	radius: string;
	transform: string;
	readingType: string;
}
